service:
  name: IsTodayMeetballsDay-API

plugins:
  - serverless-webpack
  
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-north-1

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: /
          method: get
          cors: true